version: '3.8'

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  db:
    container_name: canyon-db
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 970E95B5FFEEE
    networks:
      - backend
      - frontend
    volumes:
      - ./sql/data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  auto-patcher-server:
    container_name: canyon-auto-patcher
    build: 
      context: ./src/auto-patcher-server
      dockerfile: Dockerfile  # This line is optional if your file is named Dockerfile
    volumes:
    - ./src/auto-patcher-server/patches:/app/patches  # Corrected path
    networks:
      - frontend
    ports:
      - "1338:1338"  # Map the port to the host
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    command: ["node", "server.js"]  # Replace with your start command
